2019-04-09 18:08:21,330 ERROR: Exception on /profile [GET] [in c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\main\routes.py", line 78, in profile
    devices=current_user.devices, User=current_user)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\templates\profile.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\templates\base.html", line 84, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\templates\profile.html", line 70, in block "app_content"
    <input class="form hidden" name = "guest_access_status" value="{{Device.guest_access}}"/>
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'Device' is undefined
2019-04-09 18:08:24,143 ERROR: Exception on /profile [GET] [in c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\main\routes.py", line 78, in profile
    devices=current_user.devices, User=current_user)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\templates\profile.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\templates\base.html", line 84, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\KevinK\PycharmProjects\Plantwaterer\WateringSite\templates\profile.html", line 70, in block "app_content"
    <input class="form hidden" name = "guest_access_status" value="{{Device.guest_access}}"/>
  File "c:\users\kevink\pycharmprojects\plantwaterer\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'Device' is undefined
